# Generated by Django 5.0.3 on 2024-03-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
    ]
